<?xml version="1.0" ?><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="text" indent="no"/><xsl:template match="/data"><![CDATA[<font face=Tahoma size=2><span style="line-height:107%;">Dear&#160;</span>]]><xsl:choose><xsl:when test="contact/salutation"><xsl:value-of select="contact/salutation" /></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><![CDATA[&#160;]]><xsl:choose><xsl:when test="contact/lastname"><xsl:value-of select="contact/lastname" /></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><![CDATA[ ]]><xsl:choose><xsl:when test="account/name"><xsl:value-of select="account/name" /></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><![CDATA[</font><div><span style="line-height:107%;"><font face=Tahoma size=2><br></font></span></div><div><span style="line-height:107%;"><span style="line-height:107%;color:rgb(51, 51, 51);"><font face=Tahoma size=2>Thank you for your recent feedback, we do apologise&#160;and appreciate
the opportunity to resolve your complaint. We have now had an opportunity to
investigate and would like to offer you compensation.<br>
<br>
As a reminder you told us…<br>
]]><xsl:choose><xsl:when test="incident/description"><xsl:value-of select="incident/description" /></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><![CDATA[ <br>
</font></span></span></div><div><span style="line-height:107%;"><span style="line-height:107%;color:rgb(51, 51, 51);"><font face=Tahoma size=2><br></font></span></span></div><div><span style="line-height:107%;"><span style="line-height:107%;color:rgb(51, 51, 51);"><font face=Tahoma size=2><span style="line-height:107%;">We would like to offer you compensation to the value of&#160;]]><xsl:choose><xsl:when test="incident/tc_offeredamountdecision/@name"><xsl:value-of select="incident/tc_offeredamountdecision/@name" /></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><![CDATA[ </span><br></font></span></span></div><div><span style="line-height:107%;"><span style="line-height:107%;color:rgb(51, 51, 51);"><span style="line-height:107%;"><font face=Tahoma size=2><br></font></span></span></span></div><div><span style="line-height:107%;"><span style="line-height:107%;"><span style="line-height:107%;"><p class=MsoNormal style="color:rgb(51, 51, 51);line-height:normal;"><font face=Tahoma size=2>We have various compensation options available, so please
contact our Rep or Connected Service to discuss.<br><br>
We look forward to hearing from you.<span style="color:black;"></span></font></p><p class=MsoNormal style="color:rgb(51, 51, 51);line-height:normal;"><font face=Tahoma size=2><img style="" src="http://cdn.thomascook.com/images/uploads/icons/thomas_cook_logo_450px.png"><br></font></p><p class=MsoNormal style="color:rgb(51, 51, 51);line-height:normal;"><font face=Tahoma size=2>Customer Relations<span style="color:black;"></span></font></p><p class=MsoNormal style="color:rgb(51, 51, 51);line-height:normal;">

</p><p class=MsoNormal style="line-height:normal;"><font face=Tahoma size=2><font color="#333333">Tel No: 01733 224 814</font><br><font color="#333333">
Opening Hours: 9am-8pm Mon-Fri, 9am-5pm Sat.</font><br>
<br><font color="#333333">Airtours&#160;is a trading name of Thomas Cook Tour Operations Limited.</font><br><font color="#333333">
Registered Office: The Thomas Cook Business Park, Coningsby Road, Peterborough,
PE3 8SB</font><br><font color="#333333">
Registered in England No. 3772199</font></font><span style="font-family:Tahoma, sans-serif;color:black;font-size:9pt;font-size:9pt;"></span></p></span></span></span></div>]]></xsl:template></xsl:stylesheet>