USE [master]
GO

/****** Object:  Database [Tc.DataMigration]    Script Date: 9/19/2017 4:29:33 PM ******/
CREATE DATABASE [Tc.DataMigration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tc.DataMigration', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Tc.DataMigration.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tc.DataMigration_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Tc.DataMigration_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Tc.DataMigration] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tc.DataMigration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tc.DataMigration] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tc.DataMigration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tc.DataMigration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tc.DataMigration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tc.DataMigration] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tc.DataMigration] SET  MULTI_USER 
GO

ALTER DATABASE [Tc.DataMigration] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tc.DataMigration] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tc.DataMigration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tc.DataMigration] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Tc.DataMigration] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tc.DataMigration] SET  READ_WRITE 
GO


USE [Tc.DataMigration]

GO

/****** Object:  Table [dbo].[Logging]    Script Date: 9/19/2017 4:29:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Logging](
	[GBG-ID]  NVARCHAR (50) NULL,
	[FileName] [nvarchar](30) NULL,
	[FileType] [nchar](1) NULL,
	[ProcessState] [nchar](1) NULL,
	[ProcessDateTime] [datetime] NULL,
	[ErrorNo] [int] NULL,
	[ErrorDescription] [nvarchar](500) NULL,
	[StackTrace] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[MSDCountry] (
    [CountryId]      UNIQUEIDENTIFIER NOT NULL,
    [CountryISOCode] NVARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([CountryId] ASC)
)
GO

CREATE TABLE [dbo].[MSDExistingContacts] (
    [ContactId]      UNIQUEIDENTIFIER NOT NULL,
    [SourceSystemId] NVARCHAR (50) NULL
)
GO