using System.Runtime.Serialization;

namespace Tc.Crm.Service.Models
{
    //public Accommodation AccommdationkInfo { get; set; }




    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    [DataContract(Name = "bookingInfo")]
    public class BookingInformationForLog
    {
        [DataMember(Name = "booking")]
        public BookingForLog BookingForLog { get; set; }
    }

    [DataContract(Name = "booking")]
    public class BookingForLog
    {
        [DataMember(Name = "bookingIdentifier")]
        public BookingIdentifierForLog BookingIdentifierForLog { get; set; }

        
    }

    
    

    [DataContract(Name = "bookingIdentifier")]
    public class BookingIdentifierForLog
    {

       
        [DataMember(Name = "bookingNumber")]
        public string BookingNumberForLog { get; set; }

        
    }

 

  

    
}

